sudo: required
dist: trusty
addons:
  firefox: 'latest'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
script:
  - npm run build
  - xvfb-run npm test